name: CVE Scan Latest

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  cve_scan_main:
    uses: steadybit/extension-kit/.github/workflows/reusable-cve-scan.yml@main
    with:
      image_tag: 'latest'
      add_to_github_security: false
