name: ghcr-cleanup

on:
  workflow_dispatch: { }
  schedule:
    - cron: "0 8 * * 1"

jobs:
  extension-ci:
    uses: steadybit/extension-kit/.github/workflows/reusable-ghcr-cleanup.yml@main
    secrets:
      token: ${{ secrets.GHCR_CLEANUP_PAT }}
